from enum import Enum

class IncidentStatus(str, Enum):
    REPORTED = "REPORTED"
    CORROBORATING = "CORROBORATING"
    PRIORITIZED = "PRIORITIZED"
    VERIFIED = "VERIFIED"
    RESOURCE_ASSIGNED = "RESOURCE_ASSIGNED"
    RESCUE_IN_PROGRESS = "RESCUE_IN_PROGRESS"
    RESOLVED = "RESOLVED"

class LocationPrecision(str, Enum):
    HIGH = "HIGH"        # Exact GPS / precise landmark
    MEDIUM = "MEDIUM"    # Street / building complex
    LOW = "LOW"          # Coarse landmark / ward-only / "near old tree"

class SourceChannel(str, Enum):
    SMS = "SMS"
    VOICE = "VOICE"
    RADIO = "RADIO"
    SOCIAL = "SOCIAL"
    WEB = "WEB"
    SATELLITE = "SATELLITE"
    DRONE = "DRONE"

class MicroEnvironmentTag(str, Enum):
    ROOFTOP_STRANDED = "ROOFTOP_STRANDED"
    DROWNING_RISK = "DROWNING_RISK"
    DEBRIS_TRAPPED = "DEBRIS_TRAPPED"
    CRUSH_INJURY = "CRUSH_INJURY"
    CUT_OFF_ACCESS = "CUT_OFF_ACCESS"
    ELECTRICAL_HAZARD = "ELECTRICAL_HAZARD"
    NONE = "NONE"

class VulnerabilityTag(str, Enum):
    CHILDREN = "CHILDREN"
    ELDERLY = "ELDERLY"
    PREGNANT = "PREGNANT"
    DISABLED = "DISABLED"
    INJURED = "INJURED"

class HazardType(str, Enum):
    FLOOD = "FLOOD"
    BUILDING_COLLAPSE = "BUILDING_COLLAPSE"
    ROAD_WASHOUT = "ROAD_WASHOUT"
    BRIDGE_FAILURE = "BRIDGE_FAILURE"
    LANDSLIDE = "LANDSLIDE"
    ELECTRICAL_FAULT = "ELECTRICAL_FAULT"
    MEDICAL_EMERGENCY = "MEDICAL_EMERGENCY"
    SHELTER_UTILITY_FAILURE = "SHELTER_UTILITY_FAILURE"
    OTHER = "OTHER"

class VenueType(str, Enum):
    HOSPITAL = "HOSPITAL"
    PRIMARY_HEALTH_CENTER = "PRIMARY_HEALTH_CENTER"
    SCHOOL = "SCHOOL"
    SHELTER = "SHELTER"
    COMMUNITY_CENTER = "COMMUNITY_CENTER"
    POLICE_STATION = "POLICE_STATION"
    FIRE_STATION = "FIRE_STATION"
    EOC = "EOC"
    RELIEF_CENTER = "RELIEF_CENTER"
    WAREHOUSE = "WAREHOUSE"
    BRIDGE = "BRIDGE"
    ROAD_JUNCTION = "ROAD_JUNCTION"
    BOAT_LAUNCH = "BOAT_LAUNCH"
    RESCUE_STAGING_AREA = "RESCUE_STAGING_AREA"
    TELECOM_TOWER = "TELECOM_TOWER"
    POWER_SUBSTATION = "POWER_SUBSTATION"
    HELICOPTER_LANDING_AREA = "HELICOPTER_LANDING_AREA"
    OTHER = "OTHER"

class VenueStatus(str, Enum):
    OPEN = "OPEN"
    AT_RISK = "AT_RISK"
    DEGRADED = "DEGRADED"
    INACCESSIBLE = "INACCESSIBLE"
    CLOSED = "CLOSED"
    ACTIVE = "ACTIVE"
    NEAR_CAPACITY = "NEAR_CAPACITY"
    FULL = "FULL"
    OVERFLOW = "OVERFLOW"
    SURGE = "SURGE"
    CAPACITY_STRESSED = "CAPACITY_STRESSED"
    OVER_CAPACITY = "OVER_CAPACITY"

class ResourceType(str, Enum):
    BOAT = "BOAT"
    AMBULANCE = "AMBULANCE"
    EXCAVATOR = "EXCAVATOR"
    MEDICAL_TEAM = "MEDICAL_TEAM"
    HIGH_CLEARANCE_VEHICLE = "HIGH_CLEARANCE_VEHICLE"
    RESCUE_HELICOPTER = "RESCUE_HELICOPTER"

class ResourceStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    ASSIGNED = "ASSIGNED"
    EN_ROUTE = "EN_ROUTE"
    ON_SITE = "ON_SITE"
    MAINTENANCE = "MAINTENANCE"

class RoadStatus(str, Enum):
    OPEN = "OPEN"
    FLOODED = "FLOODED"
    PARTIALLY_PASSABLE = "PARTIALLY_PASSABLE"
    CLOSED = "CLOSED"
    REOPENED = "REOPENED"

class MergeReviewState(str, Enum):
    AUTO_MERGED = "AUTO_MERGED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    SEPARATE = "SEPARATE"

class PlanQuality(str, Enum):
    OPTIMAL = "PLAN QUALITY: OPTIMAL"
    FEASIBLE = "PLAN QUALITY: FEASIBLE"
    HEURISTIC_FALLBACK = "PLAN QUALITY: HEURISTIC (FALLBACK)"

class AuditActionType(str, Enum):
    REPORT_INGESTED = "REPORT_INGESTED"
    CLUSTER_CREATED = "CLUSTER_CREATED"
    CLUSTER_MERGED = "CLUSTER_MERGED"
    CLUSTER_SPLIT = "CLUSTER_SPLIT"
    INCIDENT_MERGED = "INCIDENT_MERGED"
    INCIDENT_SPLIT = "INCIDENT_SPLIT"
    PRIORITY_RECOMPUTED = "PRIORITY_RECOMPUTED"
    CONFIDENCE_UPDATED = "CONFIDENCE_UPDATED"
    DISPATCH_PLANNED = "DISPATCH_PLANNED"
    DISPATCH_APPROVED = "DISPATCH_APPROVED"
    DISPATCH_MODIFIED = "DISPATCH_MODIFIED"
    DISPATCH_OVERRIDDEN = "DISPATCH_OVERRIDDEN"
    DISPATCH_REJECTED = "DISPATCH_REJECTED"
    PLAN_REJECTED = "PLAN_REJECTED"
    REVERSE_SOS_SENT = "REVERSE_SOS_SENT"
    STATUS_CHANGED = "STATUS_CHANGED"
    VENUE_UPDATED = "VENUE_UPDATED"
    TASK_ACCEPTED = "TASK_ACCEPTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    AMPLIFY_APPROVED = "AMPLIFY_APPROVED"

class SignalType(str, Enum):
    SOS = "SOS"
    NEED = "NEED"
    UPDATE = "UPDATE"
    VAGUE = "VAGUE"
    RUMOUR = "RUMOUR"

class TelecomStatus(str, Enum):
    LIVE = "LIVE"
    DEGRADED = "DEGRADED"
    DARK = "DARK"
    PARTIAL_RECOVERY = "PARTIAL_RECOVERY"

class ProposedActionType(str, Enum):
    DISPATCH_RESOURCE = "DISPATCH_RESOURCE"
    REASSIGN_RESOURCE = "REASSIGN_RESOURCE"
    REQUEST_SATELLITE_VERIFICATION = "REQUEST_SATELLITE_VERIFICATION"
    REQUEST_DRONE_SURVEY = "REQUEST_DRONE_SURVEY"
    REQUEST_INFO = "REQUEST_INFO"
    EVACUATE_VENUE = "EVACUATE_VENUE"
    ESCALATE_ALERT = "ESCALATE_ALERT"
    RESOLVE_INCIDENT = "RESOLVE_INCIDENT"
    REOPEN_INCIDENT = "REOPEN_INCIDENT"

class NotificationChannel(str, Enum):
    SMS = "SMS"
    VOICE_IVR = "VOICE_IVR"
    CELL_BROADCAST = "CELL_BROADCAST"
    RADIO = "RADIO"
    WEB_PUSH = "WEB_PUSH"

class NotificationStatus(str, Enum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"
    ACKNOWLEDGED = "ACKNOWLEDGED"

class AdvisoryType(str, Enum):
    FLOOD_RISING = "FLOOD_RISING"
    BOAT_INBOUND = "BOAT_INBOUND"
    EVACUATION_ORDER = "EVACUATION_ORDER"
    WATER_CONTAMINATION = "WATER_CONTAMINATION"
    SHELTER_AVAILABLE = "SHELTER_AVAILABLE"
    GENERAL_ALERT = "GENERAL_ALERT"


